"""
app/api/routes/events.py

GET /events — paginated threat event listing with optional severity / status filter.
"""

from typing import Annotated

from fastapi import APIRouter, Depends, Query
from loguru import logger

from app.api.dependencies import pagination, severity_filter
from app.api.schemas import EventItem, EventsResponse
from app.config.constants import EVENTS
from app.database.mongo import get_collection

router = APIRouter()


@router.get(
    "/events",
    response_model=EventsResponse,
    summary="List threat events",
    tags=["Intelligence"],
)
def get_events(
    paging:   dict = Depends(pagination),
    severity: str | None = Depends(severity_filter),
    status: Annotated[
        str | None,
        Query(description="Filter by status: open | acknowledged | resolved"),
    ] = None,
) -> EventsResponse:
    """
    Returns paginated threat events generated by the analysis pipeline.

    Query parameters:
    - **page** — page number (default: 1)
    - **limit** — items per page (default: 20, max: 500)
    - **severity** — filter by severity: `low`, `medium`, `high`, `critical`
    - **status** — filter by status: `open`, `acknowledged`, `resolved`
    """
    col = get_collection(EVENTS)

    query: dict = {}
    if severity:
        query["severity"] = severity
    if status:
        query["status"] = status

    total = col.count_documents(query)

    cursor = (
        col.find(query, {"_id": 0})
        .sort("occurred_at", -1)    # most recent events first
        .skip(paging["skip"])
        .limit(paging["limit"])
    )

    items = []
    for doc in cursor:
        try:
            items.append(EventItem(**doc))
        except Exception as e:
            logger.warning("GET /events: skipping malformed doc — {}", e)

    logger.debug(
        "GET /events: page={} limit={} severity={} status={} → {} items (total {}).",
        paging["page"], paging["limit"], severity, status, len(items), total,
    )

    return EventsResponse(
        total = total,
        page  = paging["page"],
        limit = paging["limit"],
        items = items,
    )
