/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIdRouteImport } from './routes/agent.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/processing': typeof ProcessingRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/agent/$id': typeof AgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/processing': typeof ProcessingRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/agent/$id': typeof AgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/processing': typeof ProcessingRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/agent/$id': typeof AgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/cases'
    | '/dashboard'
    | '/processing'
    | '/recommendations'
    | '/settings'
    | '/agent/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/cases'
    | '/dashboard'
    | '/processing'
    | '/recommendations'
    | '/settings'
    | '/agent/$id'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/cases'
    | '/dashboard'
    | '/processing'
    | '/recommendations'
    | '/settings'
    | '/agent/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CasesRoute: typeof CasesRoute
  DashboardRoute: typeof DashboardRoute
  ProcessingRoute: typeof ProcessingRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  AgentIdRoute: typeof AgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CasesRoute: CasesRoute,
  DashboardRoute: DashboardRoute,
  ProcessingRoute: ProcessingRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  AgentIdRoute: AgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
